PRAGMA encoding = "UTF-8";
DROP TABLE IF EXISTS ACTOR;
CREATE TABLE ACTOR (
    rowID       INTEGER PRIMARY KEY AUTOINCREMENT,
    ACTORID      varchar(100),
    ACTORNAME	 varchar(100)
);
CREATE INDEX X_ACTOR_ID ON ACTOR (ACTORID);
