PRAGMA encoding = "UTF-8";
DROP TABLE IF EXISTS ALGORITHM;
CREATE TABLE ALGORITHM (
    rowID       INTEGER PRIMARY KEY AUTOINCREMENT,
    ALGORITHM	varchar(100),
    ALGORITHMNAME      varchar(100)
);