PRAGMA encoding = "UTF-8";
DROP TABLE IF EXISTS DOC_LABEL;
CREATE TABLE DOC_LABEL (
    rowID       INTEGER PRIMARY KEY AUTOINCREMENT,
    DOCID	varchar(100),
    LABEL      varchar(500)
);
CREATE INDEX X_LABEL ON DOC_LABEL (LABEL);