PRAGMA encoding = "UTF-8";
DROP TABLE IF EXISTS DOC_TOPIC;
CREATE TABLE DOC_TOPIC (
    rowID       INTEGER PRIMARY KEY AUTOINCREMENT,
    DOCID	varchar(100),
    TOPICID      varchar(100),
    TOPICPROP 	text
);
CREATE INDEX XX_DOC_ID ON DOC_TOPIC (DOCID);
CREATE INDEX XX_TOPIC_ID ON DOC_TOPIC (TOPICID);

