PRAGMA encoding = "UTF-8";
DROP TABLE IF EXISTS DOCUMENT;
CREATE TABLE DOCUMENT (
    rowID       INTEGER PRIMARY KEY AUTOINCREMENT,
    GROUPID	varchar(100),
    ACTORID		varchar(100),
    DOCID      varchar(100),
    DOCTITLE	varchar(100),
    DOCTIME		varchar(20),
    DOCCONTENT      text

);
CREATE INDEX X_DOC_ID ON DOCUMENT (DOCID);