PRAGMA encoding = "UTF-8";
DROP TABLE IF EXISTS TOPIC_RESULT;
CREATE TABLE TOPIC_RESULT (
    rowID       INTEGER PRIMARY KEY AUTOINCREMENT,
    ACTORID    varchar(100),
    TIMESTAMP    varchar(100),
    DOCID	varchar(1000),
    TOPICID      varchar(1000),
    PROP 	text
);
CREATE INDEX X_ACTOR_ID ON TOPIC_RESULT (ACTORID);
CREATE INDEX XX_TOPIC_ID ON TOPIC_RESULT (TOPICID);
CREATE INDEX XX_DOC_ID ON TOPIC_RESULT (DOCID);
