PRAGMA encoding = "UTF-8";
DROP TABLE IF EXISTS TOPIC;
CREATE TABLE TOPIC (
    rowID       INTEGER PRIMARY KEY AUTOINCREMENT,
    TOPICID      varchar(100),
    TOPICNAME	 varchar(100)
);
CREATE INDEX X_TOPIC_ID ON TOPIC (TOPICID);
